### ISSUE TITLE
Error in Anki 2.1.44 when converting from Markdown

### ISSUE THREAD

**Issue by joeforan76** [gregorrr/anki-auto-markdown#24]
In the latest version of Anki (2.1.44) the following error occurs when I create a card using markdown syntax and press the "Convert to/from Markdown" button. 
Looking at the error message I assume it has to do with the version update causing an incompatibility with the base64 package.

```
Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-06-11 12:30:15
Add-ons possibly involved: ⁨Auto Markdown⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 526, in handler
  File "/Users/xxx/Library/Application Support/Anki2/addons21/1030875226/editor.py", line 129, in <lambda>
    lambda field_text : onInnerTextAvailable(field_html, field_text))
  File "/Users/xxx/Library/Application Support/Anki2/addons21/1030875226/editor.py", line 139, in onInnerTextAvailable
    updated_field_html = generateHtmlFromMarkdown(field_text, field_html)
  File "/Users/xxx/Library/Application Support/Anki2/addons21/1030875226/editor.py", line 53, in generateHtmlFromMarkdown
    encoded_field_html = base64.b64encode(field_html.encode('utf-8')).decode() # needs to be string
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by joeforan76** [comment]
I found that this issue was fixed in a fork of this project
https://github.com/natfarleydev/anki-auto-markdown/issues/11
