### ISSUE TITLE
Throwing Error

### ISSUE THREAD

**Issue by philosopherdog** [gregorrr/anki-auto-markdown#25]
When I tap the icon to enabled it I get the following error. I'm on Apple Silicone M1.

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 568, in handler
  File "/Users/asceticcode/Library/Application Support/Anki2/addons21/1030875226/editor.py", line 129, in <lambda>
    lambda field_text : onInnerTextAvailable(field_html, field_text))
  File "/Users/asceticcode/Library/Application Support/Anki2/addons21/1030875226/editor.py", line 139, in onInnerTextAvailable
    updated_field_html = generateHtmlFromMarkdown(field_text, field_html)
  File "/Users/asceticcode/Library/Application Support/Anki2/addons21/1030875226/editor.py", line 53, in generateHtmlFromMarkdown
    encoded_field_html = base64.b64encode(field_html.encode('utf-8')).decode() # needs to be string
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by skplunkerin** [comment]
I'm having the same issue, on Apply MacBook Intel.

Is there a pre-requisite package or library I need to install for this Add-on to work?

**Comment by philosopherdog** [comment]
I suspect this is a python 2 issue. Modern versions of MacOS do not come with python 2 anymore.
